# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.models.ingest_commit_request import IngestCommitRequest

class TestIngestCommitRequest(unittest.TestCase):
    """IngestCommitRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngestCommitRequest:
        """Test IngestCommitRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngestCommitRequest`
        """
        model = IngestCommitRequest()
        if include_optional:
            return IngestCommitRequest(
                tenant_id = '',
                app_id = '',
                store_quarantine = True,
                retriever_backend = '',
                source_adapter = '',
                index = '',
                documents = [
                    sami_rag_client.models.ingest_document.IngestDocument(
                        doc_id = '', 
                        text = '', 
                        metadata = { }, )
                    ],
                bucket = '',
                data_source_id = ''
            )
        else:
            return IngestCommitRequest(
                documents = [
                    sami_rag_client.models.ingest_document.IngestDocument(
                        doc_id = '', 
                        text = '', 
                        metadata = { }, )
                    ],
        )
        """

    def testIngestCommitRequest(self):
        """Test IngestCommitRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
