# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from sami_rag_client.models.ingest_document import IngestDocument

class TestIngestDocument(unittest.TestCase):
    """IngestDocument unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> IngestDocument:
        """Test IngestDocument
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `IngestDocument`
        """
        model = IngestDocument()
        if include_optional:
            return IngestDocument(
                doc_id = '',
                text = '',
                metadata = { }
            )
        else:
            return IngestDocument(
                text = '',
        )
        """

    def testIngestDocument(self):
        """Test IngestDocument"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
