# coding: utf-8

"""
    Enterprise Connection Adapter

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 0.1.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.signed_url_payload import SignedUrlPayload

class TestSignedUrlPayload(unittest.TestCase):
    """SignedUrlPayload unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignedUrlPayload:
        """Test SignedUrlPayload
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignedUrlPayload`
        """
        model = SignedUrlPayload()
        if include_optional:
            return SignedUrlPayload(
                jobs = [
                    openapi_client.models.job.Job(
                        id = '', 
                        signed_url = '', 
                        file_name = '', 
                        policy_packs = [
                            ''
                            ], 
                        file_size = 56, 
                        enhanced_privacy_mode = True, )
                    ]
            )
        else:
            return SignedUrlPayload(
                jobs = [
                    openapi_client.models.job.Job(
                        id = '', 
                        signed_url = '', 
                        file_name = '', 
                        policy_packs = [
                            ''
                            ], 
                        file_size = 56, 
                        enhanced_privacy_mode = True, )
                    ],
        )
        """

    def testSignedUrlPayload(self):
        """Test SignedUrlPayload"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
