# coding: utf-8

"""
    RAG Defender Unified Gateway

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from sami_rag_client.models.ingest_document import IngestDocument
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class IngestCommitRequest(BaseModel):
    """
    IngestCommitRequest
    """ # noqa: E501
    tenant_id: Optional[StrictStr] = None
    app_id: Optional[StrictStr] = None
    store_quarantine: Optional[StrictBool] = True
    retriever_backend: Optional[StrictStr] = None
    source_adapter: Optional[StrictStr] = None
    index: Optional[StrictStr] = None
    documents: List[IngestDocument]
    bucket: Optional[StrictStr] = None
    data_source_id: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["tenant_id", "app_id", "store_quarantine", "retriever_backend", "source_adapter", "index", "documents", "bucket", "data_source_id"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of IngestCommitRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in documents (list)
        _items = []
        if self.documents:
            for _item_documents in self.documents:
                if _item_documents:
                    _items.append(_item_documents.to_dict())
            _dict['documents'] = _items
        # set to None if tenant_id (nullable) is None
        # and model_fields_set contains the field
        if self.tenant_id is None and "tenant_id" in self.model_fields_set:
            _dict['tenant_id'] = None

        # set to None if app_id (nullable) is None
        # and model_fields_set contains the field
        if self.app_id is None and "app_id" in self.model_fields_set:
            _dict['app_id'] = None

        # set to None if retriever_backend (nullable) is None
        # and model_fields_set contains the field
        if self.retriever_backend is None and "retriever_backend" in self.model_fields_set:
            _dict['retriever_backend'] = None

        # set to None if source_adapter (nullable) is None
        # and model_fields_set contains the field
        if self.source_adapter is None and "source_adapter" in self.model_fields_set:
            _dict['source_adapter'] = None

        # set to None if index (nullable) is None
        # and model_fields_set contains the field
        if self.index is None and "index" in self.model_fields_set:
            _dict['index'] = None

        # set to None if bucket (nullable) is None
        # and model_fields_set contains the field
        if self.bucket is None and "bucket" in self.model_fields_set:
            _dict['bucket'] = None

        # set to None if data_source_id (nullable) is None
        # and model_fields_set contains the field
        if self.data_source_id is None and "data_source_id" in self.model_fields_set:
            _dict['data_source_id'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of IngestCommitRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "tenant_id": obj.get("tenant_id"),
            "app_id": obj.get("app_id"),
            "store_quarantine": obj.get("store_quarantine") if obj.get("store_quarantine") is not None else True,
            "retriever_backend": obj.get("retriever_backend"),
            "source_adapter": obj.get("source_adapter"),
            "index": obj.get("index"),
            "documents": [IngestDocument.from_dict(_item) for _item in obj["documents"]] if obj.get("documents") is not None else None,
            "bucket": obj.get("bucket"),
            "data_source_id": obj.get("data_source_id")
        })
        return _obj


